### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-neumannmueller-stageflow#2]
Perhaps [this](https://github.com/bitfocus/companion-module-neumannmueller-stageflow/blob/main/index.js#L63) should be `type: 'number` instead of `'textinput'`? 

https://github.com/bitfocus/companion-module-neumannmueller-stageflow/blob/main/index.js#L169-L171 You don't appear to be using the callback passed in here. Should this really be trying to reconnect? socket.io will handle reconnection by itself without you needing to recreate the socket.

https://github.com/bitfocus/companion-module-neumannmueller-stageflow/blob/main/index.js#L245 It would be good to check that `this.socket` is defined inside here, as it may not be and that will result in an error or crash

I think that the feedbacks you have defined need some work https://github.com/bitfocus/companion-module-neumannmueller-stageflow/blob/main/feedback.js
A general comment about them is that some of them could be done as boolean feedbacks, so that the user isnt tied into changing only the bg/fg colours fields that you give them https://github.com/bitfocus/companion/wiki/Feedback
* 'start_btn' isnt using the 'pause_*' inputs. As it only uses two states, it would be nicer to do one state as a boolean feedback and let the other state use the buttons default style. 
* 'reset_btn' is perfect candidate to be a boolean feedback
* 'btn_active' could be a boolean feedback. Also `feedback.options.key` doesnt look to be an option, so Im pretty sure this feedback will never activate
* 'setMinSec' and 'preset' and 'setMessage', these are all named the same which will be really confusing to the user. Additionally, they shouldn't check the value of `bank.text` like that, as there is no guarantee that the feedback will be rechecked when the text changes. 

A very minor thing, some of the presets are setting feedback options that don't exist. This probably isnt an issue, but would be good to not define

**Comment by jonkad** [comment]
Hey @Julusian 

Thanks for your time and reviewing the code!
I have tried to implement it as best as I can. I hope it fits now. 

Cheers, Jonathan
